version: '3.8'

services:
  mongo-db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      # antes tenia guiones, usarlos es incorrecto.
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db